import Head from 'next/head';
import { useContext, useEffect, useState } from 'react';
import Footer from '../components/Footer';
import Header from '../components/Header';
import LoginModal from '../components/loginModal/LoginModal';
import PasswordForgotten from '../components/passwordForgotten/PasswordForgotten';
import SignUpModal from '../components/signUpModal/SignUpModal';
import styles from './index.module.css';
import UserContext from '../context/UserContext';
import VerificationModal from '../components/verificationModal/verificationModal';

export default function Home() {
 const [isOpen, setIsOpen] = useState(false);
 const [signUpModalIsOpen, setSignUpModalIsOpen] = useState(false);
 const [passwordForgottenModal, setPasswordForgottenModal] = useState(false);
 const [verificationModal, setVerificationModal] = useState(false);

 const { user, path } = useContext(UserContext);

 useEffect(() => {
  if (path === '/passwordRecovery') {
   setIsOpen(true);
  }
 }, [path]);

 return (
  <>
   {user && (
    <>
     <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
     </Head>
     <div className={styles.container}>
      <Header setIsOpen={setIsOpen} />
      <Footer author={'Luciano Polo'} />
      {isOpen && (
       <LoginModal
        setIsOpen={setIsOpen}
        setSignUpModalIsOpen={setSignUpModalIsOpen}
        setPasswordForgottenModal={setPasswordForgottenModal}
        setVerificationModal={setVerificationModal}
       />
      )}
      {signUpModalIsOpen && (
       <SignUpModal
        setSignUpModalIsOpen={setSignUpModalIsOpen}
        setVerificationModal={setVerificationModal}
       />
      )}
      {passwordForgottenModal && (
       <PasswordForgotten
        setPasswordForgottenModal={setPasswordForgottenModal}
       />
      )}
      {verificationModal && (
       <VerificationModal
        setVerificationModal={setVerificationModal}
        setIsOpen={setIsOpen}
       />
      )}
     </div>
    </>
   )}
  </>
 );
}
